/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/CardList.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    LoadingDataBox: typeof import('./src/components/LoadingDataBox.vue')['default']
    NodataBox: typeof import('./src/components/NodataBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
